import 'package:drift/drift.dart';

/// Read-optimised projection of `claim_events` (spec §5.2).
///
/// Never hand-edited: every row is regenerated by `ClaimProjector` whenever
/// new claims land. Deleting this whole table and rebuilding it from the log
/// must always be a no-op in terms of observable state.
@DataClassName('PersonRow')
class Persons extends Table {
  TextColumn get id => text()();

  TextColumn get fullName => text().named('full_name').nullable()();

  /// The birth year exactly as claimed, e.g. `"around 1932"`. Oral family
  /// history is approximate, so the raw text is preserved verbatim and
  /// [birthYear] holds only the parsed form used for sorting.
  TextColumn get birthYearRaw => text().named('birth_year_raw').nullable()();

  IntColumn get birthYear => integer().named('birth_year').nullable()();

  TextColumn get birthPlace => text().named('birth_place').nullable()();

  TextColumn get gender => text().nullable()();

  BoolColumn get isDeceased =>
      boolean().named('is_deceased').withDefault(const Constant(false))();

  TextColumn get photoMediaId => text().named('photo_media_id').nullable()();

  DateTimeColumn get lastUpdatedAt =>
      dateTime().named('last_updated_at').nullable()();

  /// True when the latest claim retracted this person entirely. Kept as a flag
  /// rather than a row delete so the projection mirrors the log exactly.
  BoolColumn get isRetracted =>
      boolean().named('is_retracted').withDefault(const Constant(false))();

  @override
  Set<Column> get primaryKey => {id};
}
